using System.Collections.Generic;
using System.Globalization;

namespace FreeScreenshot.Core.Localization;

/// <summary>
/// Tiny, dependency-free i18n. Picks the system UI language (CA / ES / EN)
/// at startup; everything else is hardcoded English-fallback.
/// </summary>
public static class Strings
{
    public const string DonationUrl = "https://freedolia.com/donate";
    public const string SupportUrl  = "https://freedolia.com/freescreenshot";

    public static string Current { get; private set; } = "en";

    public static IReadOnlyList<string> Available => new[] { "ca", "es", "en" };

    /// <summary>Pick best language from system, then load it.</summary>
    public static void InitFromSystem()
    {
        var two = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToLowerInvariant();
        SetLang(All.ContainsKey(two) ? two : "en");
    }

    public static void SetLang(string lang) => Current = All.ContainsKey(lang) ? lang : "en";

    public static string T(string key)
    {
        if (All.TryGetValue(Current, out var dict) && dict.TryGetValue(key, out var v)) return v;
        if (All["en"].TryGetValue(key, out var fallback)) return fallback;
        return key;
    }

    // ---- the dictionary ----
    private static readonly Dictionary<string, Dictionary<string, string>> All = new()
    {
        ["ca"] = new()
        {
            ["app.tagline"] = "Captures sense embuts.",
            ["tray.tooltip"] = "FreeScreenshot",
            ["tray.balloon.title"] = "FreeScreenshot",
            ["tray.balloon.message"] = "Visc a la safata. Clic dret sobre la icona per opcions.",
            ["menu.settings"] = "Configuració…",
            ["menu.about"] = "Quant a",
            ["menu.donate"] = "Donar",
            ["menu.quit"] = "Sortir",
            ["settings.title"] = "FreeScreenshot — Configuració",
            ["settings.nav.general"] = "General",
            ["settings.nav.privacy"] = "Privacitat",
            ["settings.nav.about"] = "Quant a",
            ["settings.general.heading"] = "General",
            ["settings.general.sub"] = "Comportament de l'app a Windows.",
            ["settings.general.lang"] = "Idioma",
            ["settings.general.placeholder"] = "Aviat: dreceres, format de sortida, carpeta de captures.",
            ["settings.privacy.heading"] = "Privacitat",
            ["settings.privacy.sub"] = "Tres senyals opt-in que FreeScreenshot envia a freedolia.com. Pots desactivar-los aquí.",
            ["settings.privacy.toggle.title"] = "Compartir dades anònimes amb freedolia.com",
            ["settings.privacy.toggle.desc"] = "Inclou l'avís d'instal·lació, la comprovació silenciosa de versions noves i l'enquesta opcional en desinstal·lar.",
            ["settings.privacy.install_id_label"] = "Identificador local d'instal·lació:",
            ["settings.privacy.open_policy"] = "Llegir política de privadesa",
            ["settings.about.heading"] = "Quant a",
            ["settings.about.sub"] = "freescreenshot · una eina de freedolia.com",
            ["settings.about.version"] = "Versió",
            ["settings.about.license"] = "Llicència",
            ["settings.about.code"] = "Codi",
            ["settings.about.donate"] = "Si t'agrada, suporta el projecte",
            ["settings.about.donate.btn"] = "Donar via Stripe",
            ["settings.about.replay_onboarding"] = "Veure l'onboarding de nou",
            ["uninstall.title"] = "Per què desinstal·les FreeScreenshot?",
            ["uninstall.sub"] = "Opcional. Triga 5 segons i ens ajudaràs a millorar.",
            ["uninstall.reason.no_what_expected"] = "No és el que esperava",
            ["uninstall.reason.missing_feature"] = "Em falta una funció que necessito",
            ["uninstall.reason.too_slow"] = "Massa lent o pesat",
            ["uninstall.reason.found_alternative"] = "He trobat una alternativa millor",
            ["uninstall.reason.not_using"] = "No el faig servir",
            ["uninstall.reason.bugs"] = "Errors o crashes",
            ["uninstall.reason.temporary"] = "Reinstal·lo / temporal",
            ["uninstall.reason.other"] = "Altres",
            ["uninstall.note.placeholder"] = "Algun comentari? (opcional)",
            ["uninstall.send"] = "Enviar i tancar",
            ["uninstall.skip"] = "Saltar",
            ["common.close"] = "Tancar",
            ["capture.hint"] = "Arrossega per seleccionar · Esc per cancel·lar",
            ["capture.toast.saved.title"] = "Captura desada",
            ["capture.toast.saved.body"] = "{0} · {1} · al portapapers",
            ["capture.error.title"] = "FreeScreenshot",
            ["capture.error.hotkey_busy"] = "Ctrl+Shift+1 ja la fa servir una altra app. Canvia-la a Configuració.",
            ["onboarding.title"] = "Benvingut a FreeScreenshot",
            ["onboarding.sub"] = "La icona ja viu a la safata del sistema. Tres passos per posar-la a punt.",
            ["onboarding.step1.title"] = "1. On viu la icona",
            ["onboarding.step1.body"] = "Mira a baix a la dreta, prop del rellotge. Premi la fletxa amunt (^) per expandir la safata; la icona lime és FreeScreenshot. Arrossega-la fora del quadret expandit cap a la barra del rellotge perquè es quedi sempre visible.",
            ["onboarding.step2.title"] = "2. Com captures",
            ["onboarding.step2.body"] = "Prem Ctrl+Shift+1 des de qualsevol app. Surt un overlay fosc: arrossega per fer un rectangle, en deixar anar la captura es desa i es copia al portapapers.",
            ["onboarding.step3.title"] = "3. On es desa",
            ["onboarding.step3.body"] = "Per defecte a Imatges\\FreeScreenshot. A Configuració > General pots canviar la carpeta, mirar el menú d'opcions o desactivar el tracking.",
            ["onboarding.done"] = "Provem-ho",
            ["history.menu_header"] = "Captures recents",
            ["history.empty"] = "(cap captura encara)",
            ["history.open_folder"] = "Obrir carpeta de captures",
            ["settings.output.heading"] = "Sortida",
            ["settings.output.folder"] = "Carpeta de captures",
            ["settings.output.browse"] = "Canviar…",
            ["settings.output.open"] = "Obrir carpeta",
            ["settings.capture.heading"] = "Captura",
            ["settings.capture.editor.title"] = "Obrir editor després de capturar",
            ["settings.capture.editor.desc"] = "Surt l'editor d'anotacions amb la captura. Pots desar amb fletxes, rectangles i text a sobre.",
            ["settings.capture.sound.title"] = "So d'obturador",
            ["settings.capture.sound.desc"] = "Reprodueix un clic suau quan es fa la captura.",
            ["editor.title"] = "FreeScreenshot — Editor",
            ["editor.tool.arrow"] = "Fletxa",
            ["editor.tool.rect"] = "Rectangle",
            ["editor.tool.text"] = "Text",
            ["editor.undo"] = "Desfer",
            ["editor.cancel"] = "Cancel·lar",
            ["editor.copy"] = "Copiar",
            ["editor.save"] = "Desar",
            ["editor.text.placeholder"] = "text aquí",
            ["capture.fullscreen.hint"] = "Pantalla sencera (Ctrl+Shift+3)",
            ["capture.window.hint"] = "Finestra activa (Ctrl+Shift+2)",
            ["capture.window.none"] = "No s'ha trobat cap finestra activa.",
            ["editor.tool.blur"] = "Difuminar",
            ["editor.tool.crop"] = "Retallar",
            ["toolbar.editor"] = "Obrir editor",
            ["toolbar.pin"] = "Fixar a la pantalla",
            ["toolbar.ocr"] = "Extreure text (OCR)",
            ["toolbar.save"] = "Desar al disc",
            ["toolbar.copy"] = "Copiar al portapapers",
            ["ocr.copied.title"] = "Text extret",
            ["ocr.copied.body"] = "{0} caràcters al portapapers",
            ["ocr.empty"] = "No s'ha trobat text llegible.",
        },
        ["es"] = new()
        {
            ["app.tagline"] = "Capturas sin enredos.",
            ["tray.tooltip"] = "FreeScreenshot",
            ["tray.balloon.title"] = "FreeScreenshot",
            ["tray.balloon.message"] = "Vivo en la bandeja. Clic derecho sobre el icono para opciones.",
            ["menu.settings"] = "Configuración…",
            ["menu.about"] = "Acerca de",
            ["menu.donate"] = "Donar",
            ["menu.quit"] = "Salir",
            ["settings.title"] = "FreeScreenshot — Configuración",
            ["settings.nav.general"] = "General",
            ["settings.nav.privacy"] = "Privacidad",
            ["settings.nav.about"] = "Acerca de",
            ["settings.general.heading"] = "General",
            ["settings.general.sub"] = "Comportamiento de la app en Windows.",
            ["settings.general.lang"] = "Idioma",
            ["settings.general.placeholder"] = "Pronto: atajos, formato de salida, carpeta de capturas.",
            ["settings.privacy.heading"] = "Privacidad",
            ["settings.privacy.sub"] = "Tres señales opt-in que FreeScreenshot envía a freedolia.com. Puedes desactivarlas aquí.",
            ["settings.privacy.toggle.title"] = "Compartir datos anónimos con freedolia.com",
            ["settings.privacy.toggle.desc"] = "Incluye el aviso de instalación, la comprobación silenciosa de versiones nuevas y la encuesta opcional al desinstalar.",
            ["settings.privacy.install_id_label"] = "Identificador local de instalación:",
            ["settings.privacy.open_policy"] = "Leer política de privacidad",
            ["settings.about.heading"] = "Acerca de",
            ["settings.about.sub"] = "freescreenshot · una herramienta de freedolia.com",
            ["settings.about.version"] = "Versión",
            ["settings.about.license"] = "Licencia",
            ["settings.about.code"] = "Código",
            ["settings.about.donate"] = "Si te gusta, apoya el proyecto",
            ["settings.about.donate.btn"] = "Donar vía Stripe",
            ["settings.about.replay_onboarding"] = "Ver onboarding de nuevo",
            ["uninstall.title"] = "¿Por qué desinstalas FreeScreenshot?",
            ["uninstall.sub"] = "Opcional. Tarda 5 segundos y nos ayudas a mejorar.",
            ["uninstall.reason.no_what_expected"] = "No es lo que esperaba",
            ["uninstall.reason.missing_feature"] = "Me falta una función que necesito",
            ["uninstall.reason.too_slow"] = "Demasiado lento o pesado",
            ["uninstall.reason.found_alternative"] = "Encontré una alternativa mejor",
            ["uninstall.reason.not_using"] = "No lo uso",
            ["uninstall.reason.bugs"] = "Errores o crashes",
            ["uninstall.reason.temporary"] = "Reinstalo / temporal",
            ["uninstall.reason.other"] = "Otros",
            ["uninstall.note.placeholder"] = "¿Algún comentario? (opcional)",
            ["uninstall.send"] = "Enviar y cerrar",
            ["uninstall.skip"] = "Saltar",
            ["common.close"] = "Cerrar",
            ["capture.hint"] = "Arrastra para seleccionar · Esc para cancelar",
            ["capture.toast.saved.title"] = "Captura guardada",
            ["capture.toast.saved.body"] = "{0} · {1} · en el portapapeles",
            ["capture.error.title"] = "FreeScreenshot",
            ["capture.error.hotkey_busy"] = "Ctrl+Shift+1 ya está en uso por otra app. Cámbiala en Configuración.",
            ["onboarding.title"] = "Bienvenido a FreeScreenshot",
            ["onboarding.sub"] = "El icono ya vive en la bandeja del sistema. Tres pasos para dejarlo a punto.",
            ["onboarding.step1.title"] = "1. Dónde vive el icono",
            ["onboarding.step1.body"] = "Mira abajo a la derecha, cerca del reloj. Pulsa la flecha arriba (^) para expandir la bandeja; el icono lime es FreeScreenshot. Arrástralo fuera del cuadro expandido hasta la barra del reloj para que quede siempre visible.",
            ["onboarding.step2.title"] = "2. Cómo capturas",
            ["onboarding.step2.body"] = "Pulsa Ctrl+Shift+1 desde cualquier app. Aparece un overlay oscuro: arrastra un rectángulo y al soltar se guarda y se copia al portapapeles.",
            ["onboarding.step3.title"] = "3. Dónde se guarda",
            ["onboarding.step3.body"] = "Por defecto en Imágenes\\FreeScreenshot. En Configuración > General puedes cambiar la carpeta, abrir el menú de opciones o desactivar el tracking.",
            ["onboarding.done"] = "Probemos",
            ["history.menu_header"] = "Capturas recientes",
            ["history.empty"] = "(ninguna captura aún)",
            ["history.open_folder"] = "Abrir carpeta de capturas",
            ["settings.output.heading"] = "Salida",
            ["settings.output.folder"] = "Carpeta de capturas",
            ["settings.output.browse"] = "Cambiar…",
            ["settings.output.open"] = "Abrir carpeta",
            ["settings.capture.heading"] = "Captura",
            ["settings.capture.editor.title"] = "Abrir editor tras capturar",
            ["settings.capture.editor.desc"] = "Aparece el editor de anotaciones con la captura. Puedes guardar con flechas, rectángulos y texto encima.",
            ["settings.capture.sound.title"] = "Sonido de obturador",
            ["settings.capture.sound.desc"] = "Reproduce un clic suave al capturar.",
            ["editor.title"] = "FreeScreenshot — Editor",
            ["editor.tool.arrow"] = "Flecha",
            ["editor.tool.rect"] = "Rectángulo",
            ["editor.tool.text"] = "Texto",
            ["editor.undo"] = "Deshacer",
            ["editor.cancel"] = "Cancelar",
            ["editor.copy"] = "Copiar",
            ["editor.save"] = "Guardar",
            ["editor.text.placeholder"] = "texto aquí",
            ["capture.fullscreen.hint"] = "Pantalla completa (Ctrl+Shift+3)",
            ["capture.window.hint"] = "Ventana activa (Ctrl+Shift+2)",
            ["capture.window.none"] = "No se encontró ninguna ventana activa.",
            ["editor.tool.blur"] = "Difuminar",
            ["editor.tool.crop"] = "Recortar",
            ["toolbar.editor"] = "Abrir editor",
            ["toolbar.pin"] = "Fijar en pantalla",
            ["toolbar.ocr"] = "Extraer texto (OCR)",
            ["toolbar.save"] = "Guardar en disco",
            ["toolbar.copy"] = "Copiar al portapapeles",
            ["ocr.copied.title"] = "Texto extraído",
            ["ocr.copied.body"] = "{0} caracteres en el portapapeles",
            ["ocr.empty"] = "No se encontró texto legible.",
        },
        ["en"] = new()
        {
            ["app.tagline"] = "Screenshots without the fuss.",
            ["tray.tooltip"] = "FreeScreenshot",
            ["tray.balloon.title"] = "FreeScreenshot",
            ["tray.balloon.message"] = "I live in the tray. Right-click the icon for options.",
            ["menu.settings"] = "Settings…",
            ["menu.about"] = "About",
            ["menu.donate"] = "Donate",
            ["menu.quit"] = "Quit",
            ["settings.title"] = "FreeScreenshot — Settings",
            ["settings.nav.general"] = "General",
            ["settings.nav.privacy"] = "Privacy",
            ["settings.nav.about"] = "About",
            ["settings.general.heading"] = "General",
            ["settings.general.sub"] = "How the app behaves on Windows.",
            ["settings.general.lang"] = "Language",
            ["settings.general.placeholder"] = "Coming soon: shortcuts, output format, capture folder.",
            ["settings.privacy.heading"] = "Privacy",
            ["settings.privacy.sub"] = "Three opt-in signals FreeScreenshot sends to freedolia.com. You can turn them off here.",
            ["settings.privacy.toggle.title"] = "Share anonymous data with freedolia.com",
            ["settings.privacy.toggle.desc"] = "Includes the install ping, the silent version check and the optional uninstall survey.",
            ["settings.privacy.install_id_label"] = "Local install identifier:",
            ["settings.privacy.open_policy"] = "Read privacy policy",
            ["settings.about.heading"] = "About",
            ["settings.about.sub"] = "freescreenshot · a freedolia.com tool",
            ["settings.about.version"] = "Version",
            ["settings.about.license"] = "License",
            ["settings.about.code"] = "Code",
            ["settings.about.donate"] = "If it helps you, support the project",
            ["settings.about.donate.btn"] = "Donate via Stripe",
            ["settings.about.replay_onboarding"] = "Show onboarding again",
            ["uninstall.title"] = "Why are you uninstalling FreeScreenshot?",
            ["uninstall.sub"] = "Optional. Takes 5 seconds and helps us improve.",
            ["uninstall.reason.no_what_expected"] = "Not what I expected",
            ["uninstall.reason.missing_feature"] = "A feature I need is missing",
            ["uninstall.reason.too_slow"] = "Too slow or heavy",
            ["uninstall.reason.found_alternative"] = "Found a better alternative",
            ["uninstall.reason.not_using"] = "I don't use it",
            ["uninstall.reason.bugs"] = "Bugs or crashes",
            ["uninstall.reason.temporary"] = "Reinstalling / temporary",
            ["uninstall.reason.other"] = "Other",
            ["uninstall.note.placeholder"] = "Any comment? (optional)",
            ["uninstall.send"] = "Send and close",
            ["uninstall.skip"] = "Skip",
            ["common.close"] = "Close",
            ["capture.hint"] = "Drag to select · Esc to cancel",
            ["capture.toast.saved.title"] = "Screenshot saved",
            ["capture.toast.saved.body"] = "{0} · {1} · copied to clipboard",
            ["capture.error.title"] = "FreeScreenshot",
            ["capture.error.hotkey_busy"] = "Ctrl+Shift+1 is already in use by another app. Change it in Settings.",
            ["onboarding.title"] = "Welcome to FreeScreenshot",
            ["onboarding.sub"] = "The icon already lives in your system tray. Three quick steps to set it up.",
            ["onboarding.step1.title"] = "1. Where the icon lives",
            ["onboarding.step1.body"] = "Look at the bottom-right, near the clock. Click the up-arrow (^) to expand the tray; the lime icon is FreeScreenshot. Drag it out of the expanded box onto the clock bar so it stays visible.",
            ["onboarding.step2.title"] = "2. How to capture",
            ["onboarding.step2.body"] = "Press Ctrl+Shift+1 from any app. A dark overlay appears: drag a rectangle and on release the shot is saved and copied to the clipboard.",
            ["onboarding.step3.title"] = "3. Where it's saved",
            ["onboarding.step3.body"] = "Default: Pictures\\FreeScreenshot. In Settings > General you can change the folder, open the menu of options, or disable tracking.",
            ["onboarding.done"] = "Let's try it",
            ["history.menu_header"] = "Recent screenshots",
            ["history.empty"] = "(no captures yet)",
            ["history.open_folder"] = "Open screenshots folder",
            ["settings.output.heading"] = "Output",
            ["settings.output.folder"] = "Screenshots folder",
            ["settings.output.browse"] = "Change…",
            ["settings.output.open"] = "Open folder",
            ["settings.capture.heading"] = "Capture",
            ["settings.capture.editor.title"] = "Open editor after capture",
            ["settings.capture.editor.desc"] = "Shows the annotation editor with the capture. You can save with arrows, rectangles, and text on top.",
            ["settings.capture.sound.title"] = "Shutter sound",
            ["settings.capture.sound.desc"] = "Plays a soft click on capture.",
            ["editor.title"] = "FreeScreenshot — Editor",
            ["editor.tool.arrow"] = "Arrow",
            ["editor.tool.rect"] = "Rectangle",
            ["editor.tool.text"] = "Text",
            ["editor.undo"] = "Undo",
            ["editor.cancel"] = "Cancel",
            ["editor.copy"] = "Copy",
            ["editor.save"] = "Save",
            ["editor.text.placeholder"] = "text here",
            ["capture.fullscreen.hint"] = "Full screen (Ctrl+Shift+3)",
            ["capture.window.hint"] = "Active window (Ctrl+Shift+2)",
            ["capture.window.none"] = "No active window found.",
            ["editor.tool.blur"] = "Blur",
            ["editor.tool.crop"] = "Crop",
            ["toolbar.editor"] = "Open editor",
            ["toolbar.pin"] = "Pin to screen",
            ["toolbar.ocr"] = "Extract text (OCR)",
            ["toolbar.save"] = "Save to disk",
            ["toolbar.copy"] = "Copy to clipboard",
            ["ocr.copied.title"] = "Text extracted",
            ["ocr.copied.body"] = "{0} characters on the clipboard",
            ["ocr.empty"] = "No readable text found.",
        },
    };
}
